# Generated by Django 6.0.5 on 2026-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='selected_outfit',
            field=models.CharField(default='m_base', max_length=64),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unlocked_outfits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
